---
sudo: required
language: python
services:
  - docker
before_install:
  - pip install ansible
  - ansible-galaxy install giovtorres.epel -p /home/travis/build/giovtorres
install:
  - pip install molecule docker-py 
script:
  - molecule test --all
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
